# File: .github/workflows/build-web.yml
name: Build, Push, and Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'frontend/**'
      - '.github/workflows/build-web.yml'

jobs:
  # ------------------------------------
  # JOB 1: Build and Push
  # ------------------------------------
  build-and-push:
    name: Build and Push Web Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_SP_CLIENT_ID }}
          password: ${{ secrets.ACR_SP_CLIENT_SECRET }}

      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/gridwatch-web:${{ github.sha }}

  # ------------------------------------
  # JOB 2: Deploy
  # ------------------------------------
  deploy:
    name: Deploy Web to Container App
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Azure Container Apps extension
        run: |
          az extension add --name containerapp --upgrade

      - name: Deploy new image
        run: |
          az containerapp update \
            --name gridwatch-web \
            --resource-group gridwatch-app-rg \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/gridwatch-web:${{ github.sha }}

      - name: Log out
        run: |
          az logout
          az cache purge